require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/employees", type: :request do

  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Employee.create! valid_attributes
      get employees_url
      expect(response).to be_successful
    end
  end

  describe "pagination" do
    # Will has joined recently so it appears first (page 1)
    # Odlest is oldest employee so it appears last (page 2)
    first_names = %w[Mukesh Rakesh Anil Sikha Anjali Henry Rahul Jack Roshan Will]

    before do
      first_names.each_with_index do |name, i|
        Employee.create!(
          first_name: name,
          last_name: "Smith",
          email: "#{name.downcase}#{i}@example.com",
          job_title: "Engineer",
          country: "India",
          salary: 50000,
          date_of_joining: i.days.ago.to_date
        )
      end
      
      # oldest employee
      Employee.create!(
        first_name: "Oldest",
        last_name: "Smith",
        email: "oldest@example.com",
        job_title: "Engineer",
        country: "India",
        salary: 50000,
        date_of_joining: 100.days.ago.to_date
      )
    end

    it "returns first page with 10 employees" do
      get employees_url
      expect(response).to have_http_status(:ok)
      expect(response.body).to include("Mukesh")
      expect(response.body).not_to include("Oldest")
    end

    it "returns second page when page=2 is passed" do
      get employees_url, params: { page: 2 }
      expect(response).to have_http_status(:ok)
      expect(response.body).to include("Oldest")
    end

    it "renders pagination links" do
      get employees_url
      expect(response.body).to include("page=2")
    end

    # per_page=5 DESC: Mukesh..Anjali on page 1, Oldest on page 3
    it "respects per_page param" do
      get employees_url, params: { per_page: 5 }
      expect(response).to have_http_status(:ok)
      expect(response.body).to include("page=2")
      expect(response.body).not_to include("Oldest")
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      employee = Employee.create! valid_attributes
      get employee_url(employee)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_employee_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      employee = Employee.create! valid_attributes
      get edit_employee_url(employee)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Employee" do
        expect {
          post employees_url, params: { employee: valid_attributes }
        }.to change(Employee, :count).by(1)
      end

      it "redirects to the created employee" do
        post employees_url, params: { employee: valid_attributes }
        expect(response).to redirect_to(employee_url(Employee.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Employee" do
        expect {
          post employees_url, params: { employee: invalid_attributes }
        }.to change(Employee, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post employees_url, params: { employee: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested employee" do
        employee = Employee.create! valid_attributes
        patch employee_url(employee), params: { employee: new_attributes }
        employee.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the employee" do
        employee = Employee.create! valid_attributes
        patch employee_url(employee), params: { employee: new_attributes }
        employee.reload
        expect(response).to redirect_to(employee_url(employee))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        employee = Employee.create! valid_attributes
        patch employee_url(employee), params: { employee: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested employee" do
      employee = Employee.create! valid_attributes
      expect {
        delete employee_url(employee)
      }.to change(Employee, :count).by(-1)
    end

    it "redirects to the employees list" do
      employee = Employee.create! valid_attributes
      delete employee_url(employee)
      expect(response).to redirect_to(employees_url)
    end
  end
end
